spring.application.name: gateway

server:
  port: 8999

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



restTemplate:
  connectTimeout: 5
  readTimeout: 5
